# Generated by Django 4.2.6 on 2023-12-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('edesc', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('erem', models.BooleanField(default=False, verbose_name='Удалить?')),
                ('fiostud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фио студента')),
                ('facul', models.CharField(blank=True, max_length=100, null=True, verbose_name='Факультет')),
                ('kafedra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кафедра')),
                ('groupnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Учебная группа')),
                ('napravlenie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Направление подготовки (специальность)')),
                ('vidpract', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вид практики')),
                ('rukpractic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Руководитель практики от маи фамилия и инициалы')),
                ('familinic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия с инициалами студента')),
                ('datasdacha', models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('datanach', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала практики')),
                ('datakonec', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания практики')),
                ('predpriat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название структурного подразделения (отдел, лаборатория)')),
                ('zadanie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Индивидуальное задание студенту ')),
                ('dataotziv', models.DateTimeField(blank=True, null=True, verbose_name='Дата отзыва')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
