# Generated by Django 4.1.7 on 2023-12-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docgurnal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gurnal',
            options={'verbose_name': 'Журнал', 'verbose_name_plural': 'Журнал'},
        ),
    ]
